/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageCustomers;

import Buisness.AirlineDirectory;
import Buisness.Airlines;
import Buisness.Customer;
import Buisness.Flights;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Harshitha
 */


public class BookSeats extends javax.swing.JPanel {
    private AirlineDirectory airDir;
     Flights fli;
     JPanel userProcessContainer;

    /**
     * Creates new form BookSeats
     */
    public BookSeats(JPanel userProcessContainer,Flights fli,AirlineDirectory airDir) {
        
         initComponents();
         
        this.userProcessContainer=userProcessContainer;
        this.fli=fli;
        this.airDir=airDir;
        
       
       
        windowCombobox.removeAllItems();
        
       for(String w :fli.getWindowList() ) {
           
           windowCombobox.addItem(w);
       }
       
       middleCombobox.removeAllItems();
       for(String m :fli.getMiddleList()) {
           
           middleCombobox.addItem(m);
       }
       
       aisleCombobox.removeAllItems();
       for(String a :fli.getAisleList()) {
           
           aisleCombobox.addItem(a);
       }
       
       
       fliNoTF.setText(fli.getFlightNumber());
       airNameTF.setText(fli.getAirlineName());
       int total=availseats();
       total = total -3;
       fli.setNoOfSeats(total);
       availseatsTF.setText(String.valueOf(fli.getNoOfSeats()));
    
    }
    
    public int availseats()
    {
        int totalseats=fli.getWindowList().size() + fli.getMiddleList().size() + fli.getAisleList().size();
        return totalseats;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowCombobox = new javax.swing.JComboBox();
        middleCombobox = new javax.swing.JComboBox();
        aisleCombobox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fnTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lnTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pnoTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        airNameTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fliNoTF = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        availseatsTF = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        emailIDTF = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 62, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        windowCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(windowCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 352, -1, -1));

        middleCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(middleCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 352, -1, -1));

        aisleCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(aisleCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(737, 352, -1, -1));

        jButton1.setBackground(new java.awt.Color(34, 167, 240));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Add Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 572, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 561, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 88, -1, -1));
        add(fnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 88, 121, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 143, -1, -1));
        add(lnTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 143, 121, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Passport :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 88, -1, -1));
        add(pnoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 88, 121, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Gender: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 143, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Airline Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 286, -1, -1));

        airNameTF.setEditable(false);
        add(airNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 286, 110, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Flight Number");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 286, -1, -1));

        fliNoTF.setEditable(false);
        add(fliNoTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 286, 110, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 343, 803, 11));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Choose Seat Number:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 363, 220, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Available Seats");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 286, -1, -1));

        availseatsTF.setEditable(false);
        add(availseatsTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 286, 44, -1));

        jButton4.setBackground(new java.awt.Color(34, 167, 240));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setText("View Bookings >>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(814, 572, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Email ID:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 209, -1, -1));
        add(emailIDTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 209, 242, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 143, 121, -1));

        jButton3.setBackground(new java.awt.Color(255, 153, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton3.setText("CUSTOMER   DETAILS");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1067, 44));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/ManageCustomers/Flight.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, -99, 275, 649));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        Customer c=airDir.addCustomer();
                
        
        c.setFirstName(fnTF.getText());
        c.setLastName(lnTF.getText());
        c.setPassportNo(pnoTF.getText());
        c.setFlightNumber(fli.getFlightNumber());
        c.setAirlineName(fli.getAirlineName());
        c.setPrice(fli.getPrice());
        c.setEmailId(emailIDTF.getText());
        
        //System.out.println("cust name is"+ c.getFirstName());
        
         String win=(String)windowCombobox.getSelectedItem();
        if(!win.equals(null)&& !win.equals("Window"))
        {
            fli.removeWindow(win);
            c.getSeatsBooked().add(win);
            
        }
        
        
        String ais=(String)aisleCombobox.getSelectedItem();
        if((!ais.equals(null))&& !ais.equals("Aisle"))
        {
            fli.removeAisle(ais);
            c.getSeatsBooked().add(ais);
            
        }
        
        String mid=(String)middleCombobox.getSelectedItem();
        if((!mid.equals(null))&& !mid.equals("Middle"))
        {
            fli.removeMiddle(mid);
            c.getSeatsBooked().add(mid);
            
        }
        
        for(String i : c.getSeatsBooked())
        {
            System.out.println("seats booked are "+i);
        }
        
         JOptionPane.showMessageDialog(null,"Customer Details added successfully !!");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
         layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        BookingsView bv=new BookingsView(userProcessContainer,airDir);
        userProcessContainer.add("BookingViePanel",bv);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airNameTF;
    private javax.swing.JComboBox aisleCombobox;
    private javax.swing.JTextField availseatsTF;
    private javax.swing.JTextField emailIDTF;
    private javax.swing.JTextField fliNoTF;
    private javax.swing.JTextField fnTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lnTF;
    private javax.swing.JComboBox middleCombobox;
    private javax.swing.JTextField pnoTF;
    private javax.swing.JComboBox windowCombobox;
    // End of variables declaration//GEN-END:variables
}
